### ISSUE TITLE
[Future addons issue]

### ISSUE THREAD

**Issue by xIsm4** [ShieldCommunity/SternalBoard#30]
1: Add "placeholders" to avoid spam on config like "<30:text:>
![image](https://user-images.githubusercontent.com/76608233/163898615-2f2177be-a840-47d1-a2c5-764a8b2b3158.png)
2: Add animated scoreboard per world.
3: Tablist addon (Integrated on the api for developers tho)
4: Add scoreboard per permissions and probly per item.
5: Add custom events (Like other plugins)
6: Scoreboard animated per permission
7: Hook into versions to verify if they're legacy or not, without NMS or Viaversion

**Comment by iAtog** [comment]
zarpado's

**Comment by xIsm4** [comment]
> zarpado's
🥵

**Comment by dinobossytnew** [comment]
atualizaaa cabroooooon

**Comment by xIsm4** [comment]
Mostly all has been added by other ways, so this issue is redundant
