### ISSUE TITLE
Formatting Bug

### ISSUE THREAD

**Issue by MatrixSystemPVP** [ShieldCommunity/SternalBoard#45]
**Describe the bug**
The Plugin does not format colors from Placeholders.

**To Reproduce**
1. Set a Line in the Config to `%luckperms_prefix%` or something similar, which will output a HEX colored String
2. Reload the config
3. Look at the Scoreboard and notice the String from that Placeholder not being formatted

**Expected behavior**
I expect it to format as if I set the line to `&#2cb2ff&lDev` directly without using any Placeholder.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39440609/226066196-1b281131-9d55-4799-89c8-43752fe4d62e.png)
![grafik](https://user-images.githubusercontent.com/39440609/226066246-730c2d23-a1d0-4f43-861f-d1cab8c68c6d.png)

**Comment by xIsm4** [comment]
> **Describe the bug** The Plugin does not format colors from Placeholders.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Set a Line in the Config to `%luckperms_prefix%` or something similar, which will output a HEX colored String
> 2. Reload the config
> 3. Look at the Scoreboard and notice the String from that Placeholder not being formatted
> 
> **Expected behavior** I expect it to format as if I set the line to `&#2cb2ff&lDev` directly without using any Placeholder.
> 
> **Screenshots** ![grafik](https://user-images.githubusercontent.com/39440609/226066196-1b281131-9d55-4799-89c8-43752fe4d62e.png) ![grafik](https://user-images.githubusercontent.com/39440609/226066246-730c2d23-a1d0-4f43-861f-d1cab8c68c6d.png)

Yes **MAIN** branch have's that PlaceHolderAPI problem with colours.

https://github.com/ShieldCommunity/SternalBoard/releases/tag/2.1.0-b2

It includes also some performance tweaks and some other features.

**Comment by MatrixSystemPVP** [comment]
Alrighty, it works with the pre-release Version.

You should probably leave this Issue open until the Version is fully released, so anyone else encountering the Problem will be able to see the answer easily ^^
It's up to you tho, how you want to handle it :)
