### ISSUE TITLE
Error Config, and tab completer

### ISSUE THREAD

**Issue by HyperByGhost** [ShieldCommunity/SternalBoard#46]
Al momento de crear la config, la crea mal, y el tab no esta completo

imagenes:

![image](https://user-images.githubusercontent.com/47264347/227824341-8c8ae878-aa23-4a07-a25c-f2b24c59bdfc.png)

![image](https://user-images.githubusercontent.com/47264347/227824396-87dceb96-6cf4-4b53-9ff7-ff1865ee0a99.png)

 - Version 1.8 shieldspigot version

**Comment by ForeignBloom226** [comment]
Hola, tengo el mismo problema con la config!
Esta misma no se genera correctamente.
![image](https://user-images.githubusercontent.com/124937324/228708404-12c0e170-b2df-4d5f-a937-9de563b4ad46.png)

**Comment by jonakls** [comment]
Hi, @ForeignBloom226  @HyperByGhost.

u can test it version please?

https://github.com/ShieldCommunity/SternalBoard/releases/tag/2.2.0

**Comment by xIsm4** [comment]
> Al momento de crear la config, la crea mal, y el tab no esta completo
> 
> imagenes:
> 
> ![image](https://user-images.githubusercontent.com/47264347/227824341-8c8ae878-aa23-4a07-a25c-f2b24c59bdfc.png)
> 
> ![image](https://user-images.githubusercontent.com/47264347/227824396-87dceb96-6cf4-4b53-9ff7-ff1865ee0a99.png)
> 
> * Version 1.8 shieldspigot version

Este error ha sido solucionado ya, descarga la última versión oficial en Spigot

**Comment by jonakls** [comment]
Closed to negative response from the stakeholders
