### ISSUE TITLE
Can't use PlaceholderAPI Animations

### ISSUE THREAD

**Issue by 01maxzie** [ShieldCommunity/SternalBoard#54]
I am trying to use those rainbow animations in PlaceholderAPI but they don't work. Am I doing something wrong?

**Comment by xism4** [comment]
> I am trying to use those rainbow animations in PlaceholderAPI but they don't work. Am I doing something wrong?

Could you explain better your problem?

**Comment by xism4** [comment]
I think this is a missconfiguration problem, also you didn't answer so i will close it. Re-open if you need more information
