### ISSUE TITLE
Flickering when using refresh rates under 1.

### ISSUE THREAD

**Issue by 01maxzie** [ShieldCommunity/SternalBoard#55]
So my problem is, if you set the refresh rate for the scoreboard to anything less than 1, it will start flickering. Is there any way to fix this or is this not fixable?

**Comment by xism4** [comment]
> So my problem is, if you set the refresh rate for the scoreboard to anything less than 1, it will start flickering. Is there any way to fix this or is this not fixable?

Well the interval should be possitive always.

**Comment by 01maxzie** [comment]
So, basically, I can't use numbers like 0.1 or 0.5 when setting the refresh rate. Is that correct?

**Comment by xism4** [comment]
> So, basically, I can't use numbers like 0.1 or 0.5 when setting the refresh rate. Is that correct?

I can add subdecimals, but shouldn't work for now

**Comment by xism4** [comment]
I will close this for now, re-open if you need help.
