### ISSUE TITLE
RGB Doesn't work

### ISSUE THREAD

**Issue by PepeePL** [ShieldCommunity/SternalBoard#58]
**Describe the bug**

**To Reproduce**
1. Format a line using hex. `&#ff0000T&#ff2929E&#ff5151S&#ff7a7aT`
2. Scoreboard shows Minecraft's default colors only.

![image](https://github.com/ShieldCommunity/SternalBoard/assets/65291003/9389ff97-85bc-42fa-b9a9-1dd7f45aaf60)

**Expected behavior**
Scoreboard shows formatting in RGB

**Comment by xism4** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Format a line using hex. `&#ff0000T&#ff2929E&#ff5151S&#ff7a7aT`
> 2. Scoreboard shows Minecraft's default colors only.
> 
> ![image](https://user-images.githubusercontent.com/65291003/273403763-9389ff97-85bc-42fa-b9a9-1dd7f45aaf60.png)
> 
> **Expected behavior** Scoreboard shows formatting in RGB

Try to use MiniMessage gradient or other format

**Comment by xism4** [comment]
Closed since no response.
