### ISSUE TITLE
Scoreboard por region (WorldGuard)

### ISSUE THREAD

**Issue by zLunarKnight** [ShieldCommunity/SternalBoard#61]
¡Hola! una de mis sugerencia es implementar scoreboard por regiones y que tenga compatibilidad con worldguard y tambien estaria bueno que las scoreboard tenga prioridades esto para evitar si tienes un rango ejemplo admin y tengas permisos por debajo de 3 rangos no se muestre otro scoreboard mas que el que tenga mas prioridad, nose si ya sea compatible con el plugin https://www.spigotmc.org/resources/%E2%9C%85-king-of-the-hill-1-7-1-18-%E2%80%8D%E2%9C%85-20-discount.6832/ pero si no tiene compatibilidad tambien implementarlo estaria bueno (antes se bugeaba al mostrar el scoreboard de koth y el de sternalboard no aparecia mas) bueno esa seria todas mis sugerencias!

**Comment by xism4** [comment]
> ¡Hola! una de mis sugerencia es implementar scoreboard por regiones y que tenga compatibilidad con worldguard y tambien estaria bueno que las scoreboard tenga prioridades esto para evitar si tienes un rango ejemplo admin y tengas permisos por debajo de 3 rangos no se muestre otro scoreboard mas que el que tenga mas prioridad, nose si ya sea compatible con el plugin

Si, es compatible el plugin de KOTH. Voy a implementar la scoreboard por regiones
