### ISSUE TITLE
Only show fb-2727288282

### ISSUE THREAD

**Issue by Grizzlybln** [ShieldCommunity/SternalBoard#63]
**Describe the bug**
Install tze plugin , edit config.yml and start , you see only "fb-182736253" not a board

**Screenshots**
Not able while not can create screenshots (Not Supported By Device)

**Device (please complete the following information):**
 - Android MC 1.20.2
- spigotmc.com
 - 2.2.7

**Additional context**
We cant fix it by editing any data :/

**Comment by xism4** [comment]
> * Android MC 1.20.2

Sorry i can't replicate this, SternalBoard 2.2.7 (main branch) works properly

**Comment by xism4** [comment]
> > * Android MC 1.20.2
> 
> Sorry i can't replicate this, SternalBoard 2.2.7 (main branch) works properly

I will close by no response
