### ISSUE TITLE
How to modify the TAB?

### ISSUE THREAD

**Issue by theblower21** [ShieldCommunity/SternalBoard#64]
Hello, in the configurable files of SternalBoard I do not see an option to configure the TAB, and that is the default
![Captura de pantalla 2023-12-10 172933](https://github.com/ShieldCommunity/SternalBoard/assets/153467501/6f19c827-7ab8-46d5-86a5-e09555464c40)

**Comment by xism4** [comment]
> Hello, in the configurable files of SternalBoard I do not see an option to configure the TAB, and that is the default ![Captura de pantalla 2023-12-10 172933](https://private-user-images.githubusercontent.com/153467501/289394538-6f19c827-7ab8-46d5-86a5-e09555464c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDQwODQsIm5iZiI6MTcwMjM0Mzc4NCwicGF0aCI6Ii8xNTM0Njc1MDEvMjg5Mzk0NTM4LTZmMTljODI3LTdhYjgtNDZkNS04NmE1LWUwOTU1NTQ2NGM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwMTE2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTk4N2U1MTc1YTAzYTFhZWNmZmU2MjQ0ZDc3YzQ3OGVjMjJmNGIyMzJlZDAyODcyMDljZGVkMTIxODk0MmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TmAhnkPX6kgzeezow_uAo-vjQNUWo22G-22RA8ffxGA)

Try restarting your configuration, this should bring up the new settings. For future versions the new configuration system at software startup will add or vice versa the new changes without the need for that.
