### ISSUE TITLE
Purple colors aren't turning out correctly

### ISSUE THREAD

**Issue by GTFP-MC** [ShieldCommunity/SternalBoard#67]
**Describe the bug**
I used a gradient to turn the sidebars a gradient color. Some of these colors aren't appearing correctly. Especially egregious are the colors #643098 and #60379A (which are the |-lines at the bottom-left of the sidebar)

**To Reproduce**
![image](https://github.com/ShieldCommunity/SternalBoard/assets/122840237/b5fc8665-6386-4a8b-bc49-16130c718166)

**Expected behavior**
Be a similar color to the ones above it since its a gradient #80199A-#60379A
(see the chat text color in the screenshot below)

**Screenshots**
![image](https://github.com/ShieldCommunity/SternalBoard/assets/122840237/90e21fec-3673-4ca3-a21d-8f431d2832d2)
![image](https://github.com/ShieldCommunity/SternalBoard/assets/122840237/1a6acda2-22f9-4585-8de0-8885ef8c0830)

**Desktop (please complete the following information):**
 - Windows 11
 - SternalBoard-2.2.4-all
 - Minecraft 1.20.1

**Comment by GTFP-MC** [comment]
The next line %moregradients_custom_#5C3E9C-#0ABDC6_---------------------% continues the gradient and it looks normal

**Comment by GTFP-MC** [comment]
if i put in the "blue" colors in that gradient it looks normal, but if i put it on its own it turns blue

![image](https://github.com/ShieldCommunity/SternalBoard/assets/122840237/86c5fb29-633e-4d82-8695-3f6cd794e106)
![image](https://github.com/ShieldCommunity/SternalBoard/assets/122840237/30d6fe36-fddb-4023-ae70-c32be103b85c)

**Comment by GTFP-MC** [comment]
![image](https://github.com/ShieldCommunity/SternalBoard/assets/122840237/588b9a20-1bf1-4c25-ad32-bd210f21703d)

what it looks like corrected. notice the ones above the blue |-lines also now changed

**Comment by xism4** [comment]
> ![image](https://private-user-images.githubusercontent.com/122840237/305577900-588b9a20-1bf1-4c25-ad32-bd210f21703d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMTg2MDQsIm5iZiI6MTcwODIxODMwNCwicGF0aCI6Ii8xMjI4NDAyMzcvMzA1NTc3OTAwLTU4OGI5YTIwLTFiZjEtNGMyNS1hZDMyLWJkMjEwZjIxNzAzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQwMTA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTMxYjdlMjJiZmNkZGE4NTcwMDc4MzU4ZjlhNzAzZTU0Mjc0Zjc2ZmIyN2UyZjIyY2Q2YjZiZTU4MzY3OTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b8s8Tk2QIJsONExx8BBzHNNMatjTKJASKCvbfBHj34k)
> 
> what it looks like corrected. notice the ones above the blue |-lines also now changed

Can you test with MiniMessage format?

**Comment by Archeol** [comment]
(i'm a related account to OP)

what is a minimessage format?

**Comment by xism4** [comment]
> (i'm a related account to OP)
> 
> what is a minimessage format?

MiniMessage is an ideal and simple format that SternalBoard supports, which with the color names you can create your scoreboard without using an RGB generator.

**Comment by xism4** [comment]
> > (i'm a related account to OP)
> > what is a minimessage format?
> 
> MiniMessage is an ideal and simple format that SternalBoard supports, which with the color names you can create your scoreboard without using an RGB generator.

I'll close for now.
