### ISSUE TITLE
Persist toggled data

### ISSUE THREAD

**Issue by Folas1337** [ShieldCommunity/SternalBoard#69]
**Is your feature request related to a problem? Please describe.**
Nope, I wouldn't consider this a problem necessarily.

**Describe the solution you'd like**
I would like it so that if you once '/board toggle', it stays turned off, at least as a config option.
So basically add the option in the config for
```yaml
settings:
  persist-toggle-data: false
```
(or something similar)
and if you set it to true, it will save it to disk who has it turned on or off and you'll not always have to use '/board toggle' just to turn it back off :)

**Describe alternatives you've considered**
I could probably create two scoreboards with permissions and create a custom command or something that sets the permission and removes it but that's super tedious.

**Additional context**
Don't really have anything here :D

**Comment by xism4** [comment]
> **Is your feature request related to a problem? Please describe.** Nope, I wouldn't consider this a problem necessarily.
> 
> **Describe the solution you'd like** I would like it so that if you once '/board toggle', it stays turned off, at least as a config option. So basically add the option in the config for
> 
> ```yaml
> settings:
>   persist-toggle-data: false
> ```
> 
> (or something similar) and if you set it to true, it will save it to disk who has it turned on or off and you'll not always have to use '/board toggle' just to turn it back off :)
> 
> **Describe alternatives you've considered** I could probably create two scoreboards with permissions and create a custom command or something that sets the permission and removes it but that's super tedious.
> 
> **Additional context** Don't really have anything here :D

Hi, thanks for suggest that feature. Is really necesary? Because i would not like to save on a file or db that information. Maybe cache for some time.

**Comment by Folas1337** [comment]
I personally think it's necessary but I have actually found another solution to what I was doing with SternalBoard so I have now stopped using SternalBoard altogether.

If you still want to do this, go ahead, otherwise feel free to close this issue :)

**Comment by xism4** [comment]
Ok, i'll add it.
