### ISSUE TITLE
scoreboard values not working.

### ISSUE THREAD

**Issue by veroxsity** [ShieldCommunity/SternalBoard#75]
**Describe the bug**
None of the values are working for the scoreboard

![image](https://github.com/user-attachments/assets/596822e0-18e3-4b2a-8555-6464cbd92dff)

**Expected behavior**
The values should show correctly

**Desktop (please complete the following information):**
Game version 1.21.1

**Comment by xism4** [comment]
> **Describe the bug** None of the values are working for the scoreboard
> 
> ![image](https://private-user-images.githubusercontent.com/123596279/395816023-596822e0-18e3-4b2a-8555-6464cbd92dff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDY5NDQsIm5iZiI6MTczNDQ0NjY0NCwicGF0aCI6Ii8xMjM1OTYyNzkvMzk1ODE2MDIzLTU5NjgyMmUwLTE4ZTMtNGIyYS04NTU1LTY0NjRjYmQ5MmRmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNDQ0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjFlODYzZDQ2NzUzOTkxODk4N2ZiNDM3NDAyNmM3ZTc0M2ZiZTUwYTZlZmRkNWQ5Y2ZhMDBmMjQ1ZGQyMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5GfhUZTSfR9AlNKRWp0_WGWrOEz6_NQJYLLkKrhEqTw)
> 
> **Expected behavior** The values should show correctly
> 
> **Desktop (please complete the following information):** Game version 1.21.1

Hello, you need to use placeholderapi for those values.
